#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: ABP_Rifle_AnimLayer_TPP

#include "Basic.hpp"

#include "ABP_Hero_TPP_ItemBaseLayer_structs.hpp"


namespace SDK
{

// ScriptStruct ABP_Rifle_AnimLayer_TPP.ABP_Rifle_AnimLayer_TPP_C.AnimBlueprintGeneratedConstantData
// 0x0000 (0x0710 - 0x0710)
struct ABP_Rifle_AnimLayer_TPP::FAnimBlueprintGeneratedConstantData : public ABP_Hero_TPP_ItemBaseLayer::FAnimBlueprintGeneratedConstantData
{
};
static_assert(alignof(ABP_Rifle_AnimLayer_TPP::FAnimBlueprintGeneratedConstantData) == 0x000008, "Wrong alignment on ABP_Rifle_AnimLayer_TPP::FAnimBlueprintGeneratedConstantData");
static_assert(sizeof(ABP_Rifle_AnimLayer_TPP::FAnimBlueprintGeneratedConstantData) == 0x000710, "Wrong size on ABP_Rifle_AnimLayer_TPP::FAnimBlueprintGeneratedConstantData");

}

