#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: AIC_Ghost

#include "Basic.hpp"

#include "AICommon_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass AIC_Ghost.AIC_Ghost_C
// 0x0000 (0x0560 - 0x0560)
class AAIC_Ghost_C final : public AP2GhostAIController
{
public:
	static class UClass* StaticClass()	 // 0x0
	{
		return StaticBPGeneratedClassImpl<"AIC_Ghost_C">();
	}
	static class AAIC_Ghost_C* GetDefaultObj()	 // 0x0
	{
		return GetDefaultObjImpl<AAIC_Ghost_C>();
	}
};
static_assert(alignof(AAIC_Ghost_C) == 0x000008, "Wrong alignment on AAIC_Ghost_C");
static_assert(sizeof(AAIC_Ghost_C) == 0x000560, "Wrong size on AAIC_Ghost_C");

}

