#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_Action_InventoryOpen

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_Action_InventoryOpen.BP_Action_InventoryOpen_C
// 0x0000 (0x01F8 - 0x01F8)
class UBP_Action_InventoryOpen_C final : public UP2Action_InventoryOpen
{
public:
	static class UClass* StaticClass()	 // 0x0
	{
		return StaticBPGeneratedClassImpl<"BP_Action_InventoryOpen_C">();
	}
	static class UBP_Action_InventoryOpen_C* GetDefaultObj()	 // 0x0
	{
		return GetDefaultObjImpl<UBP_Action_InventoryOpen_C>();
	}
};
static_assert(alignof(UBP_Action_InventoryOpen_C) == 0x000008, "Wrong alignment on UBP_Action_InventoryOpen_C");
static_assert(sizeof(UBP_Action_InventoryOpen_C) == 0x0001F8, "Wrong size on UBP_Action_InventoryOpen_C");

}

