#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ApplyBooster_Resist_Exp_Injury

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_ApplyBooster_Resist_Exp_Injury.BP_ApplyBooster_Resist_Exp_Injury_C
// 0x0000 (0x0038 - 0x0038)
class UBP_ApplyBooster_Resist_Exp_Injury_C final : public UP2ConsumeAction_Stimulant
{
public:
	static class UClass* StaticClass()	 // 0x0
	{
		return StaticBPGeneratedClassImpl<"BP_ApplyBooster_Resist_Exp_Injury_C">();
	}
	static class UBP_ApplyBooster_Resist_Exp_Injury_C* GetDefaultObj()	 // 0x0
	{
		return GetDefaultObjImpl<UBP_ApplyBooster_Resist_Exp_Injury_C>();
	}
};
static_assert(alignof(UBP_ApplyBooster_Resist_Exp_Injury_C) == 0x000008, "Wrong alignment on UBP_ApplyBooster_Resist_Exp_Injury_C");
static_assert(sizeof(UBP_ApplyBooster_Resist_Exp_Injury_C) == 0x000038, "Wrong size on UBP_ApplyBooster_Resist_Exp_Injury_C");

}

