#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_BattleTorch_Light_TPP_VFX_Niagara_Component

#include "Basic.hpp"


namespace SDK::Params
{

// Function BP_BattleTorch_Light_TPP_VFX_Niagara_Component.BP_BattleTorch_Light_TPP_VFX_Niagara_Component_C.ExecuteUbergraph_BP_BattleTorch_Light_TPP_VFX_Niagara_Component
// 0x0004 (0x0004 - 0x0000)
struct BP_BattleTorch_Light_TPP_VFX_Niagara_Component_C_ExecuteUbergraph_BP_BattleTorch_Light_TPP_VFX_Niagara_Component final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(BP_BattleTorch_Light_TPP_VFX_Niagara_Component_C_ExecuteUbergraph_BP_BattleTorch_Light_TPP_VFX_Niagara_Component) == 0x000004, "Wrong alignment on BP_BattleTorch_Light_TPP_VFX_Niagara_Component_C_ExecuteUbergraph_BP_BattleTorch_Light_TPP_VFX_Niagara_Component");
static_assert(sizeof(BP_BattleTorch_Light_TPP_VFX_Niagara_Component_C_ExecuteUbergraph_BP_BattleTorch_Light_TPP_VFX_Niagara_Component) == 0x000004, "Wrong size on BP_BattleTorch_Light_TPP_VFX_Niagara_Component_C_ExecuteUbergraph_BP_BattleTorch_Light_TPP_VFX_Niagara_Component");
static_assert(offsetof(BP_BattleTorch_Light_TPP_VFX_Niagara_Component_C_ExecuteUbergraph_BP_BattleTorch_Light_TPP_VFX_Niagara_Component, EntryPoint) == 0x000000, "Member 'BP_BattleTorch_Light_TPP_VFX_Niagara_Component_C_ExecuteUbergraph_BP_BattleTorch_Light_TPP_VFX_Niagara_Component::EntryPoint' has a wrong offset!");

}

