#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_ContractStaticCondition_Anomaly

#include "Basic.hpp"

#include "BP_ContractStaticCondition_Anomaly_classes.hpp"
#include "BP_ContractStaticCondition_Anomaly_parameters.hpp"


namespace SDK
{

// Function BP_ContractStaticCondition_Anomaly.BP_ContractStaticCondition_Anomaly_C.CheckStaticCondition
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent, Const)
// Parameters:
// const class UP2ContractData*            InContractData                                         (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const class UObject*                    InWorldContextObject                                   (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UBP_ContractStaticCondition_Anomaly_C::CheckStaticCondition(const class UP2ContractData* InContractData, const class UObject* InWorldContextObject) const
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_ContractStaticCondition_Anomaly_C", "CheckStaticCondition");

	Params::BP_ContractStaticCondition_Anomaly_C_CheckStaticCondition Parms{};

	Parms.InContractData = InContractData;
	Parms.InWorldContextObject = InWorldContextObject;

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

