#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_CharacterGameplayCueTranslator

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_CharacterGameplayCueTranslator.BP_CharacterGameplayCueTranslator_C
// 0x0000 (0x00F8 - 0x00F8)
class UBP_CharacterGameplayCueTranslator_C final : public UP2CueTranslator_Character
{
public:
	static class UClass* StaticClass()	 // 0x0
	{
		return StaticBPGeneratedClassImpl<"BP_CharacterGameplayCueTranslator_C">();
	}
	static class UBP_CharacterGameplayCueTranslator_C* GetDefaultObj()	 // 0x0
	{
		return GetDefaultObjImpl<UBP_CharacterGameplayCueTranslator_C>();
	}
};
static_assert(alignof(UBP_CharacterGameplayCueTranslator_C) == 0x000008, "Wrong alignment on UBP_CharacterGameplayCueTranslator_C");
static_assert(sizeof(UBP_CharacterGameplayCueTranslator_C) == 0x0000F8, "Wrong size on UBP_CharacterGameplayCueTranslator_C");

}

