#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_EndOfRaidSequence

#include "Basic.hpp"

#include "BP_EndOfRaidSequence_classes.hpp"
#include "BP_EndOfRaidSequence_parameters.hpp"


namespace SDK
{

// Function BP_EndOfRaidSequence.BP_EndOfRaidSequence_C.ExecuteUbergraph_BP_EndOfRaidSequence
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EndOfRaidSequence_C::ExecuteUbergraph_BP_EndOfRaidSequence(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EndOfRaidSequence_C", "ExecuteUbergraph_BP_EndOfRaidSequence");

	Params::BP_EndOfRaidSequence_C_ExecuteUbergraph_BP_EndOfRaidSequence Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EndOfRaidSequence.BP_EndOfRaidSequence_C.GetPulseCurveFloat
// (Public, HasOutParams, BlueprintCallable, BlueprintEvent, BlueprintPure)
// Parameters:
// double                                  InTime                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double*                                 OutTime                                                (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double*                                 OutIntensity                                           (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EndOfRaidSequence_C::GetPulseCurveFloat(double InTime, double* OutTime, double* OutIntensity)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EndOfRaidSequence_C", "GetPulseCurveFloat");

	Params::BP_EndOfRaidSequence_C_GetPulseCurveFloat Parms{};

	Parms.InTime = InTime;

	UObject::ProcessEvent(Func, &Parms);

	if (OutTime != nullptr)
		*OutTime = Parms.OutTime;

	if (OutIntensity != nullptr)
		*OutIntensity = Parms.OutIntensity;
}


// Function BP_EndOfRaidSequence.BP_EndOfRaidSequence_C.PlayShake
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class UAnimSpringSimData*         CameraShake                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const class UAnimSpringSimData*         WeaponShake                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// float                                   NormalizedMagnitude                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// double                                  Falloff                                                (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void ABP_EndOfRaidSequence_C::PlayShake(const class UAnimSpringSimData* CameraShake, const class UAnimSpringSimData* WeaponShake, float NormalizedMagnitude, double Falloff)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EndOfRaidSequence_C", "PlayShake");

	Params::BP_EndOfRaidSequence_C_PlayShake Parms{};

	Parms.CameraShake = CameraShake;
	Parms.WeaponShake = WeaponShake;
	Parms.NormalizedMagnitude = NormalizedMagnitude;
	Parms.Falloff = Falloff;

	UObject::ProcessEvent(Func, &Parms);
}


// Function BP_EndOfRaidSequence.BP_EndOfRaidSequence_C.ReceiveBeginPlay
// (Event, Protected, BlueprintEvent)

void ABP_EndOfRaidSequence_C::ReceiveBeginPlay()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EndOfRaidSequence_C", "ReceiveBeginPlay");

	UObject::ProcessEvent(Func, nullptr);
}


// Function BP_EndOfRaidSequence.BP_EndOfRaidSequence_C.ShakeFX
// (BlueprintCallable, BlueprintEvent)

void ABP_EndOfRaidSequence_C::ShakeFX()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("BP_EndOfRaidSequence_C", "ShakeFX");

	UObject::ProcessEvent(Func, nullptr);
}

}

