#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_IncendiaryGrenade_Default_Throwable_Fire

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_IncendiaryGrenade_Default_Throwable_Fire.BP_IncendiaryGrenade_Default_Throwable_Fire_C
// 0x0010 (0x0488 - 0x0478)
class ABP_IncendiaryGrenade_Default_Throwable_Fire_C final : public AP2ThrowableActor_Fire
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x0478(0x0008)(ZeroConstructor, Transient, DuplicateTransient)
	class UNiagaraComponent*                      Effect;                                            // 0x0480(0x0008)(Edit, BlueprintVisible, ZeroConstructor, DisableEditOnInstance, InstancedReference, NoDestructor, HasGetValueTypeHash)

public:
	void ExecuteUbergraph_BP_IncendiaryGrenade_Default_Throwable_Fire(int32 EntryPoint)	 // 0xae1e64;
	void PlayTrigger_BP()	 // 0xae1e64;
	void ReceiveDestroyed()	 // 0xae1e64;

public:
	static class UClass* StaticClass()	 // 0x0
	{
		return StaticBPGeneratedClassImpl<"BP_IncendiaryGrenade_Default_Throwable_Fire_C">();
	}
	static class ABP_IncendiaryGrenade_Default_Throwable_Fire_C* GetDefaultObj()	 // 0x0
	{
		return GetDefaultObjImpl<ABP_IncendiaryGrenade_Default_Throwable_Fire_C>();
	}
};
static_assert(alignof(ABP_IncendiaryGrenade_Default_Throwable_Fire_C) == 0x000008, "Wrong alignment on ABP_IncendiaryGrenade_Default_Throwable_Fire_C");
static_assert(sizeof(ABP_IncendiaryGrenade_Default_Throwable_Fire_C) == 0x000488, "Wrong size on ABP_IncendiaryGrenade_Default_Throwable_Fire_C");
static_assert(offsetof(ABP_IncendiaryGrenade_Default_Throwable_Fire_C, UberGraphFrame) == 0x000478, "Member 'ABP_IncendiaryGrenade_Default_Throwable_Fire_C::UberGraphFrame' has a wrong offset!");
static_assert(offsetof(ABP_IncendiaryGrenade_Default_Throwable_Fire_C, Effect) == 0x000480, "Member 'ABP_IncendiaryGrenade_Default_Throwable_Fire_C::Effect' has a wrong offset!");

}

