#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BP_StunLarge_CS

#include "Basic.hpp"

#include "GameplayCameras_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass BP_StunLarge_CS.BP_StunLarge_CS_C
// 0x0000 (0x00F0 - 0x00F0)
class UBP_StunLarge_CS_C final : public UDefaultCameraShakeBase
{
public:
	static class UClass* StaticClass()	 // 0x0
	{
		return StaticBPGeneratedClassImpl<"BP_StunLarge_CS_C">();
	}
	static class UBP_StunLarge_CS_C* GetDefaultObj()	 // 0x0
	{
		return GetDefaultObjImpl<UBP_StunLarge_CS_C>();
	}
};
static_assert(alignof(UBP_StunLarge_CS_C) == 0x000010, "Wrong alignment on UBP_StunLarge_CS_C");
static_assert(sizeof(UBP_StunLarge_CS_C) == 0x0000F0, "Wrong size on UBP_StunLarge_CS_C");

}

