#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: BPFL_AudioFunctions

#include "Basic.hpp"

#include "BPFL_AudioFunctions_classes.hpp"
#include "BPFL_AudioFunctions_parameters.hpp"


namespace SDK
{

// Function BPFL_AudioFunctions.BPFL_AudioFunctions_C.Execute Cue from Widget
// (Static, Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UWidget*                          Widget                                                 (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, InstancedReference, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              GameplayCueTag                                         (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UBPFL_AudioFunctions_C::Execute_Cue_from_Widget(class UWidget* Widget, const struct FGameplayTag& GameplayCueTag, class UObject* __WorldContext)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_AudioFunctions_C", "Execute Cue from Widget");

	Params::BPFL_AudioFunctions_C_Execute_Cue_from_Widget Parms{};

	Parms.Widget = Widget;
	Parms.GameplayCueTag = std::move(GameplayCueTag);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);
}


// Function BPFL_AudioFunctions.BPFL_AudioFunctions_C.PostEventFromConfig
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class AActor*                           Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FAkEventSlotConfig&        Config                                                 (BlueprintVisible, BlueprintReadOnly, Parm, NoDestructor)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32*                                  PlayingID                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPFL_AudioFunctions_C::PostEventFromConfig(class AActor* Character, const struct FAkEventSlotConfig& Config, class UObject* __WorldContext, int32* PlayingID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_AudioFunctions_C", "PostEventFromConfig");

	Params::BPFL_AudioFunctions_C_PostEventFromConfig Parms{};

	Parms.Character = Character;
	Parms.Config = std::move(Config);
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (PlayingID != nullptr)
		*PlayingID = Parms.PlayingID;
}


// Function BPFL_AudioFunctions.BPFL_AudioFunctions_C.PostLocalOnlyEvent
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          My_Target                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UAkAudioEvent*                    Event                                                  (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32*                                  PlayingID                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPFL_AudioFunctions_C::PostLocalOnlyEvent(class UObject* My_Target, class UAkAudioEvent* Event, class UObject* __WorldContext, int32* PlayingID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_AudioFunctions_C", "PostLocalOnlyEvent");

	Params::BPFL_AudioFunctions_C_PostLocalOnlyEvent Parms{};

	Parms.My_Target = My_Target;
	Parms.Event = Event;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (PlayingID != nullptr)
		*PlayingID = Parms.PlayingID;
}


// Function BPFL_AudioFunctions.BPFL_AudioFunctions_C.PostLocalRemoteEvents
// (Static, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// class UObject*                          Character                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UAkAudioEvent*                    Local_Event                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UAkAudioEvent*                    Remote_Allied_Event                                    (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UAkAudioEvent*                    Remote_Enemy_Event                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// class UObject*                          __WorldContext                                         (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// int32*                                  PlayingID                                              (Parm, OutParm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UBPFL_AudioFunctions_C::PostLocalRemoteEvents(class UObject* Character, class UAkAudioEvent* Local_Event, class UAkAudioEvent* Remote_Allied_Event, class UAkAudioEvent* Remote_Enemy_Event, class UObject* __WorldContext, int32* PlayingID)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = StaticClass()->GetFunction("BPFL_AudioFunctions_C", "PostLocalRemoteEvents");

	Params::BPFL_AudioFunctions_C_PostLocalRemoteEvents Parms{};

	Parms.Character = Character;
	Parms.Local_Event = Local_Event;
	Parms.Remote_Allied_Event = Remote_Allied_Event;
	Parms.Remote_Enemy_Event = Remote_Enemy_Event;
	Parms.__WorldContext = __WorldContext;

	GetDefaultObj()->ProcessEvent(Func, &Parms);

	if (PlayingID != nullptr)
		*PlayingID = Parms.PlayingID;
}

}

