#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: E_Weather_FogTypes

#include "Basic.hpp"


namespace SDK
{

// UserDefinedEnum E_Weather_FogTypes.E_Weather_FogTypes
// NumValues: 0x0005
enum class E_Weather_FogTypes : uint8
{
	NewEnumerator2                           = 0,
	NewEnumerator3                           = 1,
	NewEnumerator0                           = 2,
	NewEnumerator1                           = 3,
	E_Weather_MAX                            = 4,
};

}

