#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: FuzzySearch

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class FuzzySearch.FuzzyMatch
// 0x0028 (0x0050 - 0x0028)
class UFuzzyMatch final : public UObject
{
public:
	int32                                         SequentialBonus;                                   // 0x0028(0x0004)(ZeroConstructor, Config, GlobalConfig, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         SeparatorBonus;                                    // 0x002C(0x0004)(ZeroConstructor, Config, GlobalConfig, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         CamelBonus;                                        // 0x0030(0x0004)(ZeroConstructor, Config, GlobalConfig, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         FirstLetterBonus;                                  // 0x0034(0x0004)(ZeroConstructor, Config, GlobalConfig, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         LeadingLetterPenalty;                              // 0x0038(0x0004)(ZeroConstructor, Config, GlobalConfig, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         MaxLeadingLetterPenalty;                           // 0x003C(0x0004)(ZeroConstructor, Config, GlobalConfig, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         UnmatchedLetterPenalty;                            // 0x0040(0x0004)(ZeroConstructor, Config, GlobalConfig, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         WordOrderPenalty;                                  // 0x0044(0x0004)(ZeroConstructor, Config, GlobalConfig, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	int32                                         ScoreInitValue;                                    // 0x0048(0x0004)(ZeroConstructor, Config, GlobalConfig, IsPlainOldData, NoDestructor, HasGetValueTypeHash, NativeAccessSpecifierPublic)
	uint8                                         Pad_4C[0x4];                                       // 0x004C(0x0004)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	static class UClass* StaticClass()	 // 0x0
	{
		return StaticClassImpl<"FuzzyMatch">();
	}
	static class UFuzzyMatch* GetDefaultObj()	 // 0x0
	{
		return GetDefaultObjImpl<UFuzzyMatch>();
	}
};
static_assert(alignof(UFuzzyMatch) == 0x000008, "Wrong alignment on UFuzzyMatch");
static_assert(sizeof(UFuzzyMatch) == 0x000050, "Wrong size on UFuzzyMatch");
static_assert(offsetof(UFuzzyMatch, SequentialBonus) == 0x000028, "Member 'UFuzzyMatch::SequentialBonus' has a wrong offset!");
static_assert(offsetof(UFuzzyMatch, SeparatorBonus) == 0x00002C, "Member 'UFuzzyMatch::SeparatorBonus' has a wrong offset!");
static_assert(offsetof(UFuzzyMatch, CamelBonus) == 0x000030, "Member 'UFuzzyMatch::CamelBonus' has a wrong offset!");
static_assert(offsetof(UFuzzyMatch, FirstLetterBonus) == 0x000034, "Member 'UFuzzyMatch::FirstLetterBonus' has a wrong offset!");
static_assert(offsetof(UFuzzyMatch, LeadingLetterPenalty) == 0x000038, "Member 'UFuzzyMatch::LeadingLetterPenalty' has a wrong offset!");
static_assert(offsetof(UFuzzyMatch, MaxLeadingLetterPenalty) == 0x00003C, "Member 'UFuzzyMatch::MaxLeadingLetterPenalty' has a wrong offset!");
static_assert(offsetof(UFuzzyMatch, UnmatchedLetterPenalty) == 0x000040, "Member 'UFuzzyMatch::UnmatchedLetterPenalty' has a wrong offset!");
static_assert(offsetof(UFuzzyMatch, WordOrderPenalty) == 0x000044, "Member 'UFuzzyMatch::WordOrderPenalty' has a wrong offset!");
static_assert(offsetof(UFuzzyMatch, ScoreInitValue) == 0x000048, "Member 'UFuzzyMatch::ScoreInitValue' has a wrong offset!");

}

