#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Dbno

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Dbno.GA_Dbno_C
// 0x0000 (0x0518 - 0x0518)
class UGA_Dbno_C final : public UP2Ability_Dbno
{
public:
	static class UClass* StaticClass()	 // 0x0
	{
		return StaticBPGeneratedClassImpl<"GA_Dbno_C">();
	}
	static class UGA_Dbno_C* GetDefaultObj()	 // 0x0
	{
		return GetDefaultObjImpl<UGA_Dbno_C>();
	}
};
static_assert(alignof(UGA_Dbno_C) == 0x000008, "Wrong alignment on UGA_Dbno_C");
static_assert(sizeof(UGA_Dbno_C) == 0x000518, "Wrong size on UGA_Dbno_C");

}

