#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_DPV_Accelerate

#include "Basic.hpp"

#include "GA_DPV_Accelerate_classes.hpp"
#include "GA_DPV_Accelerate_parameters.hpp"


namespace SDK
{

// Function GA_DPV_Accelerate.GA_DPV_Accelerate_C.ExecuteUbergraph_GA_DPV_Accelerate
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_DPV_Accelerate_C::ExecuteUbergraph_GA_DPV_Accelerate(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DPV_Accelerate_C", "ExecuteUbergraph_GA_DPV_Accelerate");

	Params::GA_DPV_Accelerate_C_ExecuteUbergraph_GA_DPV_Accelerate Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_DPV_Accelerate.GA_DPV_Accelerate_C.K2_ActivateAbility
// (Event, Protected, BlueprintEvent)

void UGA_DPV_Accelerate_C::K2_ActivateAbility()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DPV_Accelerate_C", "K2_ActivateAbility");

	UObject::ProcessEvent(Func, nullptr);
}


// Function GA_DPV_Accelerate.GA_DPV_Accelerate_C.K2_OnEndAbility
// (Event, Protected, BlueprintEvent)
// Parameters:
// bool                                    bWasCancelled                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_DPV_Accelerate_C::K2_OnEndAbility(bool bWasCancelled)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DPV_Accelerate_C", "K2_OnEndAbility");

	Params::GA_DPV_Accelerate_C_K2_OnEndAbility Parms{};

	Parms.bWasCancelled = bWasCancelled;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GA_DPV_Accelerate.GA_DPV_Accelerate_C.OnRelease_953177EF4715425595C294A51C7F2EC7
// (BlueprintCallable, BlueprintEvent)
// Parameters:
// float                                   TimeHeld                                               (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UGA_DPV_Accelerate_C::OnRelease_953177EF4715425595C294A51C7F2EC7(float TimeHeld)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GA_DPV_Accelerate_C", "OnRelease_953177EF4715425595C294A51C7F2EC7");

	Params::GA_DPV_Accelerate_C_OnRelease_953177EF4715425595C294A51C7F2EC7 Parms{};

	Parms.TimeHeld = TimeHeld;

	UObject::ProcessEvent(Func, &Parms);
}

}

