#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Hero_CameraMode

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Hero_CameraMode.GA_Hero_CameraMode_C
// 0x0000 (0x04A0 - 0x04A0)
class UGA_Hero_CameraMode_C final : public UP2Ability_CameraMode
{
public:
	static class UClass* StaticClass()	 // 0x0
	{
		return StaticBPGeneratedClassImpl<"GA_Hero_CameraMode_C">();
	}
	static class UGA_Hero_CameraMode_C* GetDefaultObj()	 // 0x0
	{
		return GetDefaultObjImpl<UGA_Hero_CameraMode_C>();
	}
};
static_assert(alignof(UGA_Hero_CameraMode_C) == 0x000008, "Wrong alignment on UGA_Hero_CameraMode_C");
static_assert(sizeof(UGA_Hero_CameraMode_C) == 0x0004A0, "Wrong size on UGA_Hero_CameraMode_C");

}

