#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GA_Inventory_SwapMagAmmo_Hideout

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// BlueprintGeneratedClass GA_Inventory_SwapMagAmmo_Hideout.GA_Inventory_SwapMagAmmo_Hideout_C
// 0x0000 (0x0500 - 0x0500)
class UGA_Inventory_SwapMagAmmo_Hideout_C final : public UP2Ability_Inventory_SwapAmmoMag
{
public:
	static class UClass* StaticClass()	 // 0x0
	{
		return StaticBPGeneratedClassImpl<"GA_Inventory_SwapMagAmmo_Hideout_C">();
	}
	static class UGA_Inventory_SwapMagAmmo_Hideout_C* GetDefaultObj()	 // 0x0
	{
		return GetDefaultObjImpl<UGA_Inventory_SwapMagAmmo_Hideout_C>();
	}
};
static_assert(alignof(UGA_Inventory_SwapMagAmmo_Hideout_C) == 0x000008, "Wrong alignment on UGA_Inventory_SwapMagAmmo_Hideout_C");
static_assert(sizeof(UGA_Inventory_SwapMagAmmo_Hideout_C) == 0x000500, "Wrong size on UGA_Inventory_SwapMagAmmo_Hideout_C");

}

