#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: GC_StatusEffect_Bleeding

#include "Basic.hpp"

#include "GC_StatusEffect_Bleeding_classes.hpp"
#include "GC_StatusEffect_Bleeding_parameters.hpp"


namespace SDK
{

// Function GC_StatusEffect_Bleeding.GC_StatusEffect_Bleeding_C.OnEffectLevelChanged
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    Update_Status_Icon                                     (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// class AActor*                           TargetActor                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void AGC_StatusEffect_Bleeding_C::OnEffectLevelChanged(bool Update_Status_Icon, class AActor* TargetActor)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GC_StatusEffect_Bleeding_C", "OnEffectLevelChanged");

	Params::GC_StatusEffect_Bleeding_C_OnEffectLevelChanged Parms{};

	Parms.Update_Status_Icon = Update_Status_Icon;
	Parms.TargetActor = TargetActor;

	UObject::ProcessEvent(Func, &Parms);
}


// Function GC_StatusEffect_Bleeding.GC_StatusEffect_Bleeding_C.OnStatusEffectDamage
// (Public, BlueprintCallable, BlueprintEvent)

void AGC_StatusEffect_Bleeding_C::OnStatusEffectDamage()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("GC_StatusEffect_Bleeding_C", "OnStatusEffectDamage");

	UObject::ProcessEvent(Func, nullptr);
}

}

