#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: MeshDescription

#include "Basic.hpp"

#include "CoreUObject_classes.hpp"


namespace SDK
{

// Class MeshDescription.MeshDescriptionBase
// 0x02C8 (0x02F0 - 0x0028)
class UMeshDescriptionBase : public UObject
{
public:
	uint8                                         Pad_28[0x2C8];                                     // 0x0028(0x02C8)(Fixing Struct Size After Last Property [ Dumper-7 ])

public:
	void ComputePolygonTriangulation(const struct FPolygonID& PolygonID)	 // 0x64f2fdc;
	struct FEdgeID CreateEdge(const struct FVertexID& VertexID0, const struct FVertexID& VertexID1)	 // 0x64f30e4;
	void CreateEdgeWithID(const struct FEdgeID& EdgeID, const struct FVertexID& VertexID0, const struct FVertexID& VertexID1)	 // 0x64f32c4;
	struct FPolygonID CreatePolygon(const struct FPolygonGroupID& PolygonGroupID, TArray<struct FVertexInstanceID>* VertexInstanceIDs, TArray<struct FEdgeID>* NewEdgeIDs)	 // 0x64f347c;
	struct FPolygonGroupID CreatePolygonGroup()	 // 0x64f3850;
	void CreatePolygonGroupWithID(const struct FPolygonGroupID& PolygonGroupID)	 // 0x64f3880;
	void CreatePolygonWithID(const struct FPolygonID& PolygonID, const struct FPolygonGroupID& PolygonGroupID, TArray<struct FVertexInstanceID>* VertexInstanceIDs, TArray<struct FEdgeID>* NewEdgeIDs)	 // 0x64f398c;
	struct FTriangleID CreateTriangle(const struct FPolygonGroupID& PolygonGroupID, const TArray<struct FVertexInstanceID>& VertexInstanceIDs, TArray<struct FEdgeID>* NewEdgeIDs)	 // 0x64f3b88;
	void CreateTriangleWithID(const struct FTriangleID& TriangleID, const struct FPolygonGroupID& PolygonGroupID, const TArray<struct FVertexInstanceID>& VertexInstanceIDs, TArray<struct FEdgeID>* NewEdgeIDs)	 // 0x64f3f5c;
	struct FVertexID CreateVertex()	 // 0x64f4158;
	struct FVertexInstanceID CreateVertexInstance(const struct FVertexID& VertexID)	 // 0x64f4188;
	void CreateVertexInstanceWithID(const struct FVertexInstanceID& VertexInstanceID, const struct FVertexID& VertexID)	 // 0x64f42a8;
	void CreateVertexWithID(const struct FVertexID& VertexID)	 // 0x64f43e4;
	void DeleteEdge(const struct FEdgeID& EdgeID, TArray<struct FVertexID>* OrphanedVertices)	 // 0x64f44f0;
	void DeletePolygon(const struct FPolygonID& PolygonID, TArray<struct FEdgeID>* OrphanedEdges, TArray<struct FVertexInstanceID>* OrphanedVertexInstances, TArray<struct FPolygonGroupID>* OrphanedPolygonGroups)	 // 0x64f47d0;
	void DeletePolygonGroup(const struct FPolygonGroupID& PolygonGroupID)	 // 0x64f4c34;
	void DeleteTriangle(const struct FTriangleID& TriangleID, TArray<struct FEdgeID>* OrphanedEdges, TArray<struct FVertexInstanceID>* OrphanedVertexInstances, TArray<struct FPolygonGroupID>* OrphanedPolygonGroupsPtr)	 // 0x64f4d50;
	void DeleteVertex(const struct FVertexID& VertexID)	 // 0x64f51b4;
	void DeleteVertexInstance(const struct FVertexInstanceID& VertexInstanceID, TArray<struct FVertexID>* OrphanedVertices)	 // 0x64f52cc;
	void Empty()	 // 0x64f55ac;
	void ReserveNewEdges(int32 NumberOfNewEdges)	 // 0x64fb548;
	void ReserveNewPolygonGroups(int32 NumberOfNewPolygonGroups)	 // 0x64fb608;
	void ReserveNewPolygons(const int32 NumberOfNewPolygons)	 // 0x64fb6e0;
	void ReserveNewTriangles(int32 NumberOfNewTriangles)	 // 0x64fb7b8;
	void ReserveNewVertexInstances(int32 NumberOfNewVertexInstances)	 // 0x64fb548;
	void ReserveNewVertices(int32 NumberOfNewVertices)	 // 0x64fb890;
	void ReversePolygonFacing(const struct FPolygonID& PolygonID)	 // 0x64fb950;
	void SetPolygonPolygonGroup(const struct FPolygonID& PolygonID, const struct FPolygonGroupID& PolygonGroupID)	 // 0x64fba58;
	void SetPolygonVertexInstances(const struct FPolygonID& PolygonID, const TArray<struct FVertexInstanceID>& VertexInstanceIDs)	 // 0x64fbc3c;
	void SetVertexPosition(const struct FVertexID& VertexID, const struct FVector& Position)	 // 0x64fbd68;

	void GetEdgeConnectedPolygons(const struct FEdgeID& EdgeID, TArray<struct FPolygonID>* OutConnectedPolygonIDs) const	 // 0x64f55c4;
	void GetEdgeConnectedTriangles(const struct FEdgeID& EdgeID, TArray<struct FTriangleID>* OutConnectedTriangleIDs) const	 // 0x64f58a4;
	int32 GetEdgeCount() const	 // 0x64f5b9c;
	struct FVertexID GetEdgeVertex(const struct FEdgeID& EdgeID, int32 VertexNumber) const	 // 0x64f5bc8;
	void GetEdgeVertices(const struct FEdgeID& EdgeID, TArray<struct FVertexID>* OutVertexIDs) const	 // 0x64f5d70;
	int32 GetNumEdgeConnectedPolygons(const struct FEdgeID& EdgeID) const	 // 0x64f5e9c;
	int32 GetNumEdgeConnectedTriangles(const struct FEdgeID& EdgeID) const	 // 0x64f5fe0;
	int32 GetNumPolygonGroupPolygons(const struct FPolygonGroupID& PolygonGroupID) const	 // 0x64f610c;
	int32 GetNumPolygonInternalEdges(const struct FPolygonID& PolygonID) const	 // 0x64f6238;
	int32 GetNumPolygonTriangles(const struct FPolygonID& PolygonID) const	 // 0x64f6364;
	int32 GetNumPolygonVertices(const struct FPolygonID& PolygonID) const	 // 0x64f6490;
	int32 GetNumVertexConnectedEdges(const struct FVertexID& VertexID) const	 // 0x64f65b4;
	int32 GetNumVertexConnectedPolygons(const struct FVertexID& VertexID) const	 // 0x64f66dc;
	int32 GetNumVertexConnectedTriangles(const struct FVertexID& VertexID) const	 // 0x64f67ac;
	int32 GetNumVertexInstanceConnectedPolygons(const struct FVertexInstanceID& VertexInstanceID) const	 // 0x64f68d0;
	int32 GetNumVertexInstanceConnectedTriangles(const struct FVertexInstanceID& VertexInstanceID) const	 // 0x64f69a0;
	int32 GetNumVertexVertexInstances(const struct FVertexID& VertexID) const	 // 0x64f6acc;
	void GetPolygonAdjacentPolygons(const struct FPolygonID& PolygonID, TArray<struct FPolygonID>* OutPolygonIDs) const	 // 0x64f6bf4;
	int32 GetPolygonCount() const	 // 0x64f6ed4;
	int32 GetPolygonGroupCount() const	 // 0x64f6f00;
	void GetPolygonGroupPolygons(const struct FPolygonGroupID& PolygonGroupID, TArray<struct FPolygonID>* OutPolygonIDs) const	 // 0x64f6f2c;
	void GetPolygonInternalEdges(const struct FPolygonID& PolygonID, TArray<struct FEdgeID>* OutEdgeIDs) const	 // 0x64f7220;
	void GetPolygonPerimeterEdges(const struct FPolygonID& PolygonID, TArray<struct FEdgeID>* OutEdgeIDs) const	 // 0x64f7500;
	struct FPolygonGroupID GetPolygonPolygonGroup(const struct FPolygonID& PolygonID) const	 // 0x64f77e0;
	void GetPolygonTriangles(const struct FPolygonID& PolygonID, TArray<struct FTriangleID>* OutTriangleIDs) const	 // 0x64f7910;
	void GetPolygonVertexInstances(const struct FPolygonID& PolygonID, TArray<struct FVertexInstanceID>* OutVertexInstanceIDs) const	 // 0x64f7c08;
	void GetPolygonVertices(const struct FPolygonID& PolygonID, TArray<struct FVertexID>* OutVertexIDs) const	 // 0x64f7d34;
	void GetTriangleAdjacentTriangles(const struct FTriangleID& TriangleID, TArray<struct FTriangleID>* OutTriangleIDs) const	 // 0x64f8014;
	int32 GetTriangleCount() const	 // 0x64f82f4;
	void GetTriangleEdges(const struct FTriangleID& TriangleID, TArray<struct FEdgeID>* OutEdgeIDs) const	 // 0x64f8320;
	struct FPolygonID GetTrianglePolygon(const struct FTriangleID& TriangleID) const	 // 0x64f844c;
	struct FPolygonGroupID GetTrianglePolygonGroup(const struct FTriangleID& TriangleID) const	 // 0x64f857c;
	struct FVertexInstanceID GetTriangleVertexInstance(const struct FTriangleID& TriangleID, int32 Index_0) const	 // 0x64f86ac;
	void GetTriangleVertexInstances(const struct FTriangleID& TriangleID, TArray<struct FVertexInstanceID>* OutVertexInstanceIDs) const	 // 0x64f8854;
	void GetTriangleVertices(const struct FTriangleID& TriangleID, TArray<struct FVertexID>* OutVertexIDs) const	 // 0x64f8980;
	void GetVertexAdjacentVertices(const struct FVertexID& VertexID, TArray<struct FVertexID>* OutAdjacentVertexIDs) const	 // 0x64f8aac;
	void GetVertexConnectedEdges(const struct FVertexID& VertexID, TArray<struct FEdgeID>* OutEdgeIDs) const	 // 0x64f8d8c;
	void GetVertexConnectedPolygons(const struct FVertexID& VertexID, TArray<struct FPolygonID>* OutConnectedPolygonIDs) const	 // 0x64f9084;
	void GetVertexConnectedTriangles(const struct FVertexID& VertexID, TArray<struct FTriangleID>* OutConnectedTriangleIDs) const	 // 0x64f9364;
	int32 GetVertexCount() const	 // 0x64f9644;
	void GetVertexInstanceConnectedPolygons(const struct FVertexInstanceID& VertexInstanceID, TArray<struct FPolygonID>* OutConnectedPolygonIDs) const	 // 0x64f9670;
	void GetVertexInstanceConnectedTriangles(const struct FVertexInstanceID& VertexInstanceID, TArray<struct FTriangleID>* OutConnectedTriangleIDs) const	 // 0x64f9950;
	int32 GetVertexInstanceCount() const	 // 0x64f9c48;
	struct FVertexInstanceID GetVertexInstanceForPolygonVertex(const struct FPolygonID& PolygonID, const struct FVertexID& VertexID) const	 // 0x64f9c74;
	struct FVertexInstanceID GetVertexInstanceForTriangleVertex(const struct FTriangleID& TriangleID, const struct FVertexID& VertexID) const	 // 0x64f9e70;
	struct FEdgeID GetVertexInstancePairEdge(const struct FVertexInstanceID& VertexInstanceID0, const struct FVertexInstanceID& VertexInstanceID1) const	 // 0x64fa054;
	struct FVertexID GetVertexInstanceVertex(const struct FVertexInstanceID& VertexInstanceID) const	 // 0x64fa238;
	struct FEdgeID GetVertexPairEdge(const struct FVertexID& VertexID0, const struct FVertexID& VertexID1) const	 // 0x64fa368;
	struct FVector GetVertexPosition(const struct FVertexID& VertexID) const	 // 0x64fa548;
	void GetVertexVertexInstances(const struct FVertexID& VertexID, TArray<struct FVertexInstanceID>* OutVertexInstanceIDs) const	 // 0x64fa62c;
	bool IsEdgeInternal(const struct FEdgeID& EdgeID) const	 // 0x64fa920;
	bool IsEdgeInternalToPolygon(const struct FEdgeID& EdgeID, const struct FPolygonID& PolygonID) const	 // 0x64faa48;
	bool IsEdgeValid(const struct FEdgeID& EdgeID) const	 // 0x64fac38;
	bool IsEmpty() const	 // 0x64fad4c;
	bool IsPolygonGroupValid(const struct FPolygonGroupID& PolygonGroupID) const	 // 0x64fad70;
	bool IsPolygonValid(const struct FPolygonID& PolygonID) const	 // 0x64fae84;
	bool IsTrianglePartOfNgon(const struct FTriangleID& TriangleID) const	 // 0x64faf98;
	bool IsTriangleValid(const struct FTriangleID& TriangleID) const	 // 0x64fb0ec;
	bool IsVertexInstanceValid(const struct FVertexInstanceID& VertexInstanceID) const	 // 0x64fb200;
	bool IsVertexOrphaned(const struct FVertexID& VertexID) const	 // 0x64fb314;
	bool IsVertexValid(const struct FVertexID& VertexID) const	 // 0x64fb438;

public:
	static class UClass* StaticClass()	 // 0x0
	{
		return StaticClassImpl<"MeshDescriptionBase">();
	}
	static class UMeshDescriptionBase* GetDefaultObj()	 // 0x0
	{
		return GetDefaultObjImpl<UMeshDescriptionBase>();
	}
};
static_assert(alignof(UMeshDescriptionBase) == 0x000008, "Wrong alignment on UMeshDescriptionBase");
static_assert(sizeof(UMeshDescriptionBase) == 0x0002F0, "Wrong size on UMeshDescriptionBase");

// Class MeshDescription.MeshDescriptionBaseBulkData
// 0x0000 (0x0028 - 0x0028)
class UMeshDescriptionBaseBulkData : public UObject
{
public:
	static class UClass* StaticClass()	 // 0x0
	{
		return StaticClassImpl<"MeshDescriptionBaseBulkData">();
	}
	static class UMeshDescriptionBaseBulkData* GetDefaultObj()	 // 0x0
	{
		return GetDefaultObjImpl<UMeshDescriptionBaseBulkData>();
	}
};
static_assert(alignof(UMeshDescriptionBaseBulkData) == 0x000008, "Wrong alignment on UMeshDescriptionBaseBulkData");
static_assert(sizeof(UMeshDescriptionBaseBulkData) == 0x000028, "Wrong size on UMeshDescriptionBaseBulkData");

}

