#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: UMG_Effect

#include "Basic.hpp"

#include "UMG_Effect_classes.hpp"
#include "UMG_Effect_parameters.hpp"


namespace SDK
{

// Function UMG_Effect.UMG_Effect_C.ExecuteUbergraph_UMG_Effect
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UUMG_Effect_C::ExecuteUbergraph_UMG_Effect(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_Effect_C", "ExecuteUbergraph_UMG_Effect");

	Params::UMG_Effect_C_ExecuteUbergraph_UMG_Effect Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function UMG_Effect.UMG_Effect_C.SetEffect
// (Event, Public, BlueprintEvent)
// Parameters:
// class UMaterialInstance*                InMaterial                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)

void UUMG_Effect_C::SetEffect(class UMaterialInstance* InMaterial)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("UMG_Effect_C", "SetEffect");

	Params::UMG_Effect_C_SetEffect Parms{};

	Parms.InMaterial = InMaterial;

	UObject::ProcessEvent(Func, &Parms);
}

}

