#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_CraftingWidget

#include "Basic.hpp"

#include "W_CraftingWidget_classes.hpp"
#include "W_CraftingWidget_parameters.hpp"


namespace SDK
{

// Function W_CraftingWidget.W_CraftingWidget_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_CraftingWidget_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_CraftingWidget_C", "PreConstruct");

	Params::W_CraftingWidget_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_CraftingWidget.W_CraftingWidget_C.ExecuteUbergraph_W_CraftingWidget
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_CraftingWidget_C::ExecuteUbergraph_W_CraftingWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_CraftingWidget_C", "ExecuteUbergraph_W_CraftingWidget");

	Params::W_CraftingWidget_C_ExecuteUbergraph_W_CraftingWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_CraftingWidget.W_CraftingWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_CraftingWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_CraftingWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_CraftingWidget.W_CraftingWidget_C.BP_OnHandleBackAction
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    ReturnValue                                            (Parm, OutParm, ZeroConstructor, ReturnParm, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

bool UW_CraftingWidget_C::BP_OnHandleBackAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_CraftingWidget_C", "BP_OnHandleBackAction");

	Params::W_CraftingWidget_C_BP_OnHandleBackAction Parms{};

	UObject::ProcessEvent(Func, &Parms);

	return Parms.ReturnValue;
}

}

