#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_FacilityBuildMode

#include "Basic.hpp"


namespace SDK::Params
{

// Function W_FacilityBuildMode.W_FacilityBuildMode_C.ExecuteUbergraph_W_FacilityBuildMode
// 0x0010 (0x0010 - 0x0000)
struct W_FacilityBuildMode_C_ExecuteUbergraph_W_FacilityBuildMode final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
	uint8                                         Pad_4[0x4];                                        // 0x0004(0x0004)(Fixing Size After Last Property [ Dumper-7 ])
	class UUMGSequencePlayer*                     CallFunc_PlayAnimation_ReturnValue;                // 0x0008(0x0008)(ZeroConstructor, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_FacilityBuildMode_C_ExecuteUbergraph_W_FacilityBuildMode) == 0x000008, "Wrong alignment on W_FacilityBuildMode_C_ExecuteUbergraph_W_FacilityBuildMode");
static_assert(sizeof(W_FacilityBuildMode_C_ExecuteUbergraph_W_FacilityBuildMode) == 0x000010, "Wrong size on W_FacilityBuildMode_C_ExecuteUbergraph_W_FacilityBuildMode");
static_assert(offsetof(W_FacilityBuildMode_C_ExecuteUbergraph_W_FacilityBuildMode, EntryPoint) == 0x000000, "Member 'W_FacilityBuildMode_C_ExecuteUbergraph_W_FacilityBuildMode::EntryPoint' has a wrong offset!");
static_assert(offsetof(W_FacilityBuildMode_C_ExecuteUbergraph_W_FacilityBuildMode, CallFunc_PlayAnimation_ReturnValue) == 0x000008, "Member 'W_FacilityBuildMode_C_ExecuteUbergraph_W_FacilityBuildMode::CallFunc_PlayAnimation_ReturnValue' has a wrong offset!");

}

