#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Facility_DeliveryTimer

#include "Basic.hpp"


namespace SDK::Params
{

// Function W_Facility_DeliveryTimer.W_Facility_DeliveryTimer_C.ExecuteUbergraph_W_Facility_DeliveryTimer
// 0x0004 (0x0004 - 0x0000)
struct W_Facility_DeliveryTimer_C_ExecuteUbergraph_W_Facility_DeliveryTimer final
{
public:
	int32                                         EntryPoint;                                        // 0x0000(0x0004)(BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
};
static_assert(alignof(W_Facility_DeliveryTimer_C_ExecuteUbergraph_W_Facility_DeliveryTimer) == 0x000004, "Wrong alignment on W_Facility_DeliveryTimer_C_ExecuteUbergraph_W_Facility_DeliveryTimer");
static_assert(sizeof(W_Facility_DeliveryTimer_C_ExecuteUbergraph_W_Facility_DeliveryTimer) == 0x000004, "Wrong size on W_Facility_DeliveryTimer_C_ExecuteUbergraph_W_Facility_DeliveryTimer");
static_assert(offsetof(W_Facility_DeliveryTimer_C_ExecuteUbergraph_W_Facility_DeliveryTimer, EntryPoint) == 0x000000, "Member 'W_Facility_DeliveryTimer_C_ExecuteUbergraph_W_Facility_DeliveryTimer::EntryPoint' has a wrong offset!");

}

