#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_ImportantMessageHud

#include "Basic.hpp"

#include "W_ImportantMessageHud_classes.hpp"
#include "W_ImportantMessageHud_parameters.hpp"


namespace SDK
{

// Function W_ImportantMessageHud.W_ImportantMessageHud_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_ImportantMessageHud_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ImportantMessageHud_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_ImportantMessageHud.W_ImportantMessageHud_C.ExecuteUbergraph_W_ImportantMessageHud
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ImportantMessageHud_C::ExecuteUbergraph_W_ImportantMessageHud(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ImportantMessageHud_C", "ExecuteUbergraph_W_ImportantMessageHud");

	Params::W_ImportantMessageHud_C_ExecuteUbergraph_W_ImportantMessageHud Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}

}

