#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Inventory_DropZone

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_Inventory_DropZone.W_Inventory_DropZone_C
// 0x0010 (0x0290 - 0x0280)
class UW_Inventory_DropZone_C final : public UP2InventoryDropZoneWidget
{
public:
	class UImage*                                 Img_RightZone_Gradient;                            // 0x0280(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)
	class USizeBox*                               SzB_VicinityDropIndicator;                         // 0x0288(0x0008)(BlueprintVisible, ExportObject, BlueprintReadOnly, ZeroConstructor, DisableEditOnInstance, InstancedReference, RepSkip, NoDestructor, PersistentInstance, HasGetValueTypeHash)

public:
	static class UClass* StaticClass()	 // 0x0
	{
		return StaticBPGeneratedClassImpl<"W_Inventory_DropZone_C">();
	}
	static class UW_Inventory_DropZone_C* GetDefaultObj()	 // 0x0
	{
		return GetDefaultObjImpl<UW_Inventory_DropZone_C>();
	}
};
static_assert(alignof(UW_Inventory_DropZone_C) == 0x000008, "Wrong alignment on UW_Inventory_DropZone_C");
static_assert(sizeof(UW_Inventory_DropZone_C) == 0x000290, "Wrong size on UW_Inventory_DropZone_C");
static_assert(offsetof(UW_Inventory_DropZone_C, Img_RightZone_Gradient) == 0x000280, "Member 'UW_Inventory_DropZone_C::Img_RightZone_Gradient' has a wrong offset!");
static_assert(offsetof(UW_Inventory_DropZone_C, SzB_VicinityDropIndicator) == 0x000288, "Member 'UW_Inventory_DropZone_C::SzB_VicinityDropIndicator' has a wrong offset!");

}

