#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_ItemDetails_ItemInfoGroup

#include "Basic.hpp"

#include "Engine_structs.hpp"
#include "Game_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_ItemDetails_ItemInfoGroup.W_ItemDetails_ItemInfoGroup_C
// 0x0008 (0x02C8 - 0x02C0)
class UW_ItemDetails_ItemInfoGroup_C final : public UP2DetailInfoGroupWidget
{
public:
	struct FPointerToUberGraphFrame               UberGraphFrame;                                    // 0x02C0(0x0008)(ZeroConstructor, Transient, DuplicateTransient)

public:
	void ExecuteUbergraph_W_ItemDetails_ItemInfoGroup(int32 EntryPoint)	 // 0xae1e64;
	void PreConstruct(bool IsDesignTime)	 // 0xae1e64;

public:
	static class UClass* StaticClass()	 // 0x0
	{
		return StaticBPGeneratedClassImpl<"W_ItemDetails_ItemInfoGroup_C">();
	}
	static class UW_ItemDetails_ItemInfoGroup_C* GetDefaultObj()	 // 0x0
	{
		return GetDefaultObjImpl<UW_ItemDetails_ItemInfoGroup_C>();
	}
};
static_assert(alignof(UW_ItemDetails_ItemInfoGroup_C) == 0x000008, "Wrong alignment on UW_ItemDetails_ItemInfoGroup_C");
static_assert(sizeof(UW_ItemDetails_ItemInfoGroup_C) == 0x0002C8, "Wrong size on UW_ItemDetails_ItemInfoGroup_C");
static_assert(offsetof(UW_ItemDetails_ItemInfoGroup_C, UberGraphFrame) == 0x0002C0, "Member 'UW_ItemDetails_ItemInfoGroup_C::UberGraphFrame' has a wrong offset!");

}

