#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_MatchmakingTimer

#include "Basic.hpp"

#include "W_MatchmakingTimer_classes.hpp"
#include "W_MatchmakingTimer_parameters.hpp"


namespace SDK
{

// Function W_MatchmakingTimer.W_MatchmakingTimer_C.ExecuteUbergraph_W_MatchmakingTimer
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MatchmakingTimer_C::ExecuteUbergraph_W_MatchmakingTimer(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MatchmakingTimer_C", "ExecuteUbergraph_W_MatchmakingTimer");

	Params::W_MatchmakingTimer_C_ExecuteUbergraph_W_MatchmakingTimer Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MatchmakingTimer.W_MatchmakingTimer_C.CloseTimerOnBP
// (Event, Protected, BlueprintEvent)

void UW_MatchmakingTimer_C::CloseTimerOnBP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MatchmakingTimer_C", "CloseTimerOnBP");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MatchmakingTimer.W_MatchmakingTimer_C.Finished_6959E0C54F271D46346642BD97B04487
// (BlueprintCallable, BlueprintEvent)

void UW_MatchmakingTimer_C::Finished_6959E0C54F271D46346642BD97B04487()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MatchmakingTimer_C", "Finished_6959E0C54F271D46346642BD97B04487");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MatchmakingTimer.W_MatchmakingTimer_C.Finished_E215660B439DB6B40902F7B592638C26
// (BlueprintCallable, BlueprintEvent)

void UW_MatchmakingTimer_C::Finished_E215660B439DB6B40902F7B592638C26()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MatchmakingTimer_C", "Finished_E215660B439DB6B40902F7B592638C26");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MatchmakingTimer.W_MatchmakingTimer_C.PlayTimerAnimationOnBP
// (Event, Protected, BlueprintEvent)

void UW_MatchmakingTimer_C::PlayTimerAnimationOnBP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MatchmakingTimer_C", "PlayTimerAnimationOnBP");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MatchmakingTimer.W_MatchmakingTimer_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MatchmakingTimer_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MatchmakingTimer_C", "PreConstruct");

	Params::W_MatchmakingTimer_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MatchmakingTimer.W_MatchmakingTimer_C.SetTimerStyle
// (Public, BlueprintCallable, BlueprintEvent)
// Parameters:
// bool                                    IsMatchmaking                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_MatchmakingTimer_C::SetTimerStyle(bool IsMatchmaking)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MatchmakingTimer_C", "SetTimerStyle");

	Params::W_MatchmakingTimer_C_SetTimerStyle Parms{};

	Parms.IsMatchmaking = IsMatchmaking;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_MatchmakingTimer.W_MatchmakingTimer_C.SetTimerStyleOnBP
// (Event, Protected, BlueprintEvent)

void UW_MatchmakingTimer_C::SetTimerStyleOnBP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MatchmakingTimer_C", "SetTimerStyleOnBP");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_MatchmakingTimer.W_MatchmakingTimer_C.ShowTimerOnBP
// (Event, Protected, BlueprintEvent)

void UW_MatchmakingTimer_C::ShowTimerOnBP()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_MatchmakingTimer_C", "ShowTimerOnBP");

	UObject::ProcessEvent(Func, nullptr);
}

}

