#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_OptionItemGroup

#include "Basic.hpp"

#include "W_OptionItemGroup_classes.hpp"
#include "W_OptionItemGroup_parameters.hpp"


namespace SDK
{

// Function W_OptionItemGroup.W_OptionItemGroup_C.ExecuteUbergraph_W_OptionItemGroup
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_OptionItemGroup_C::ExecuteUbergraph_W_OptionItemGroup(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_OptionItemGroup_C", "ExecuteUbergraph_W_OptionItemGroup");

	Params::W_OptionItemGroup_C_ExecuteUbergraph_W_OptionItemGroup Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_OptionItemGroup.W_OptionItemGroup_C.SetSubCategory_ImplementableEvent
// (Event, Protected, BlueprintEvent)
// Parameters:
// const class FString&                    InSubCategory                                          (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, HasGetValueTypeHash)

void UW_OptionItemGroup_C::SetSubCategory_ImplementableEvent(const class FString& InSubCategory)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_OptionItemGroup_C", "SetSubCategory_ImplementableEvent");

	Params::W_OptionItemGroup_C_SetSubCategory_ImplementableEvent Parms{};

	Parms.InSubCategory = std::move(InSubCategory);

	UObject::ProcessEvent(Func, &Parms);
}

}

