#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_OutgamePopupWidget

#include "Basic.hpp"

#include "W_OutgamePopupWidget_classes.hpp"
#include "W_OutgamePopupWidget_parameters.hpp"


namespace SDK
{

// Function W_OutgamePopupWidget.W_OutgamePopupWidget_C.ActiveInputAction_Implementable
// (Event, Protected, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// const class UInputAction*               InInputAction                                          (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, NoDestructor, HasGetValueTypeHash)
// const struct FGameplayTag&              InInputTag                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor, HasGetValueTypeHash)
// const struct FInputActionValue&         InputActionValue                                       (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm, NoDestructor)

void UW_OutgamePopupWidget_C::ActiveInputAction_Implementable(const class UInputAction* InInputAction, const struct FGameplayTag& InInputTag, const struct FInputActionValue& InputActionValue)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_OutgamePopupWidget_C", "ActiveInputAction_Implementable");

	Params::W_OutgamePopupWidget_C_ActiveInputAction_Implementable Parms{};

	Parms.InInputAction = InInputAction;
	Parms.InInputTag = std::move(InInputTag);
	Parms.InputActionValue = std::move(InputActionValue);

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_OutgamePopupWidget.W_OutgamePopupWidget_C.ExecuteUbergraph_W_OutgamePopupWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_OutgamePopupWidget_C::ExecuteUbergraph_W_OutgamePopupWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_OutgamePopupWidget_C", "ExecuteUbergraph_W_OutgamePopupWidget");

	Params::W_OutgamePopupWidget_C_ExecuteUbergraph_W_OutgamePopupWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_OutgamePopupWidget.W_OutgamePopupWidget_C.InitKeyFocus
// (Public, BlueprintCallable, BlueprintEvent)

void UW_OutgamePopupWidget_C::InitKeyFocus()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_OutgamePopupWidget_C", "InitKeyFocus");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_OutgamePopupWidget.W_OutgamePopupWidget_C.OnBackAction
// (BlueprintEvent)

void UW_OutgamePopupWidget_C::OnBackAction()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_OutgamePopupWidget_C", "OnBackAction");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_OutgamePopupWidget.W_OutgamePopupWidget_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_OutgamePopupWidget_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_OutgamePopupWidget_C", "PreConstruct");

	Params::W_OutgamePopupWidget_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_OutgamePopupWidget.W_OutgamePopupWidget_C.SetPopup
// (Event, Public, HasOutParams, BlueprintCallable, BlueprintEvent)
// Parameters:
// EPopupStyle                             PopupStyle                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)
// const class FText&                      Title                                                  (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const class FText&                      BodyMessage                                            (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const class FText&                      SubMessage                                             (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ReferenceParm)
// const TDelegate<void(EPopupButtonID ButtonID)>&PressedDelegate                                        (ConstParm, BlueprintVisible, BlueprintReadOnly, Parm, OutParm, ZeroConstructor, ReferenceParm, NoDestructor, HasGetValueTypeHash)

void UW_OutgamePopupWidget_C::SetPopup(EPopupStyle PopupStyle, const class FText& Title, const class FText& BodyMessage, const class FText& SubMessage, const TDelegate<void(EPopupButtonID ButtonID)>& PressedDelegate)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_OutgamePopupWidget_C", "SetPopup");

	Params::W_OutgamePopupWidget_C_SetPopup Parms{};

	Parms.PopupStyle = PopupStyle;
	Parms.Title = std::move(Title);
	Parms.BodyMessage = std::move(BodyMessage);
	Parms.SubMessage = std::move(SubMessage);
	Parms.PressedDelegate = PressedDelegate;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_OutgamePopupWidget.W_OutgamePopupWidget_C.SetPopupStyle
// (Public, HasDefaults, BlueprintCallable, BlueprintEvent)
// Parameters:
// EPopupStyle                             Selection                                              (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_OutgamePopupWidget_C::SetPopupStyle(EPopupStyle Selection)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_OutgamePopupWidget_C", "SetPopupStyle");

	Params::W_OutgamePopupWidget_C_SetPopupStyle Parms{};

	Parms.Selection = Selection;

	UObject::ProcessEvent(Func, &Parms);
}

}

