#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_PlayerStat_SourcesTooltip

#include "Basic.hpp"

#include "Game_classes.hpp"


namespace SDK
{

// WidgetBlueprintGeneratedClass W_PlayerStat_SourcesTooltip.W_PlayerStat_SourcesTooltip_C
// 0x0000 (0x02F0 - 0x02F0)
class UW_PlayerStat_SourcesTooltip_C final : public UP2AttributeEffectSourceWidget
{
public:
	static class UClass* StaticClass()	 // 0x0
	{
		return StaticBPGeneratedClassImpl<"W_PlayerStat_SourcesTooltip_C">();
	}
	static class UW_PlayerStat_SourcesTooltip_C* GetDefaultObj()	 // 0x0
	{
		return GetDefaultObjImpl<UW_PlayerStat_SourcesTooltip_C>();
	}
};
static_assert(alignof(UW_PlayerStat_SourcesTooltip_C) == 0x000008, "Wrong alignment on UW_PlayerStat_SourcesTooltip_C");
static_assert(sizeof(UW_PlayerStat_SourcesTooltip_C) == 0x0002F0, "Wrong size on UW_PlayerStat_SourcesTooltip_C");

}

