#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_Research_Cluster_Engineering_Electronics

#include "Basic.hpp"

#include "W_Research_Cluster_Engineering_Electronics_classes.hpp"
#include "W_Research_Cluster_Engineering_Electronics_parameters.hpp"


namespace SDK
{

// Function W_Research_Cluster_Engineering_Electronics.W_Research_Cluster_Engineering_Electronics_C.ExecuteUbergraph_W_Research_Cluster_Engineering_Electronics
// (Final, UbergraphFunction)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Research_Cluster_Engineering_Electronics_C::ExecuteUbergraph_W_Research_Cluster_Engineering_Electronics(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Research_Cluster_Engineering_Electronics_C", "ExecuteUbergraph_W_Research_Cluster_Engineering_Electronics");

	Params::W_Research_Cluster_Engineering_Electronics_C_ExecuteUbergraph_W_Research_Cluster_Engineering_Electronics Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_Research_Cluster_Engineering_Electronics.W_Research_Cluster_Engineering_Electronics_C.PreConstruct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// bool                                    IsDesignTime                                           (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_Research_Cluster_Engineering_Electronics_C::PreConstruct(bool IsDesignTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_Research_Cluster_Engineering_Electronics_C", "PreConstruct");

	Params::W_Research_Cluster_Engineering_Electronics_C_PreConstruct Parms{};

	Parms.IsDesignTime = IsDesignTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

