#pragma once

/*
* SDK generated by Dumper-7
*
* https://github.com/Encryqed/Dumper-7
*/

// Package: W_ToolTipMultiLineWidget

#include "Basic.hpp"

#include "W_ToolTipMultiLineWidget_classes.hpp"
#include "W_ToolTipMultiLineWidget_parameters.hpp"


namespace SDK
{

// Function W_ToolTipMultiLineWidget.W_ToolTipMultiLineWidget_C.Construct
// (BlueprintCosmetic, Event, Public, BlueprintEvent)

void UW_ToolTipMultiLineWidget_C::Construct()
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ToolTipMultiLineWidget_C", "Construct");

	UObject::ProcessEvent(Func, nullptr);
}


// Function W_ToolTipMultiLineWidget.W_ToolTipMultiLineWidget_C.ExecuteUbergraph_W_ToolTipMultiLineWidget
// (Final, UbergraphFunction, HasDefaults)
// Parameters:
// int32                                   EntryPoint                                             (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ToolTipMultiLineWidget_C::ExecuteUbergraph_W_ToolTipMultiLineWidget(int32 EntryPoint)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ToolTipMultiLineWidget_C", "ExecuteUbergraph_W_ToolTipMultiLineWidget");

	Params::W_ToolTipMultiLineWidget_C_ExecuteUbergraph_W_ToolTipMultiLineWidget Parms{};

	Parms.EntryPoint = EntryPoint;

	UObject::ProcessEvent(Func, &Parms);
}


// Function W_ToolTipMultiLineWidget.W_ToolTipMultiLineWidget_C.Tick
// (BlueprintCosmetic, Event, Public, BlueprintEvent)
// Parameters:
// const struct FGeometry&                 MyGeometry                                             (BlueprintVisible, BlueprintReadOnly, Parm, IsPlainOldData, NoDestructor)
// float                                   InDeltaTime                                            (BlueprintVisible, BlueprintReadOnly, Parm, ZeroConstructor, IsPlainOldData, NoDestructor, HasGetValueTypeHash)

void UW_ToolTipMultiLineWidget_C::Tick(const struct FGeometry& MyGeometry, float InDeltaTime)
{
	static class UFunction* Func = nullptr;

	if (Func == nullptr)
		Func = Class->GetFunction("W_ToolTipMultiLineWidget_C", "Tick");

	Params::W_ToolTipMultiLineWidget_C_Tick Parms{};

	Parms.MyGeometry = std::move(MyGeometry);
	Parms.InDeltaTime = InDeltaTime;

	UObject::ProcessEvent(Func, &Parms);
}

}

